sonar.projectKey=MedicalFlow
sonar.organization=medicalflow-org
sonar.host.url=https://sonarcloud.io
sonar.login=${env.SONAR_TOKEN}
sonar.java.source=17
sonar.sources=api-gateway,appointment-service,report-service,user-service
sonar.exclusions=**/target/**,**/*.xml,**/*.yml,**/*.yaml
